AnimalShelterClient.Solution/AnimalShelterClient/Models/Animal.cs
using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;
using System;

namespace AnimalShelterClient.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    [Required]
    public string Name { get; set; }
    [Required]
    [DisplayName("Animal Type")]
    public string AnimalType { get; set; }
    
    public static async Task<List<Animal>> GetAll()
    {
      string result = await ApiHelper.GetAll();
      List<Animal> animals = JsonSerializer.Deserialize<List<Animal>>(result);
      
      return animals;
    }

    public static async Task<Animal> Get(int id)
    {
      string result = await ApiHelper.Get(id);
      Animal animal = JsonSerializer.Deserialize<Animal>(result);
      return animal;
    }
   
    public static async Task Post(Animal animal,HttpContext context)
    {
      await ApiHelper.Post(animal, context);
    }
   
    public static async Task Delete(int id, HttpContext context)
    {
      await ApiHelper.Delete(id, context);
    }
    
    public static async Task Put(Animal animal, HttpContext context)
    {
      await ApiHelper.Put(animal, context);
    }
  }
}

AnimalShelterClient.Solution/AnimalShelterClient/Controllers/AnimalsController.cs
using AnimalShelterClient.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AnimalShelterClient.Controllers
{
  public class AnimalsController : Controller
  {
    public async Task<ActionResult> Index()
    {
      List<Animal> animals = await Animal.GetAll();
      return View(animals);
    }

    public async Task<ActionResult> Details(int id)
    {
      Animal animal = await Animal.Get(id);
      return View(animal);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Animal animal)
    {
      await Animal.Post(animal, HttpContext);
      return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<ActionResult> Remove(int id)
    {
      await Animal.Delete(id, HttpContext);
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> Edit(int id)
    {
      Animal animal = await Animal.Get(id);
      return View(animal);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(Animal animal)
    {
      await Animal.Put(animal, HttpContext);
      return RedirectToAction("Index");
    }
  }
}

AnimalShelterClient.Solution/AnimalShelterClient/Views/Animals/Create.cshtml
@using AnimalShelterClient.Models

@model AnimalShelterClient.Models.Animal

@{
  (bool,bool) values = Payload.GetValues(Context);
  @if(values.Item1 == true && values.Item2 == true)
  {
    @using(@Html.BeginForm())
    {
      @Html.LabelFor(x => x.Name)
      @Html.EditorFor(x => x.Name)
      @Html.LabelFor(x => x.AnimalType)
      @Html.EditorFor(x => x.AnimalType)
      <input type="submit" value="Create new animal profile">
    }
  }
  else if(values.Item1 == true && values.Item2 == false)
  {
    <div>
      <p>Your login token has expired. @Html.ActionLink("login","Login","Security") again to add new animals</p>
    </div>
  }
  else
  {
    <div>
      <p>You must @Html.ActionLink("login","Login","Security") in order to post animals</p>
    </div>
  }
<hr>
}

AnimalShelterClient.Solution/AnimalShelterClient/Views/Animals/Details.cshtml
@using AnimalShelterClient.Models

<p>@Model.Name</p>
<p>@Model.AnimalType</p>
<hr>

@{
  (bool,bool) values = Payload.GetValues(Context);
  @if(values.Item1 == true && values.Item2 == true)
  {
    @using (@Html.BeginForm("Remove", "Animals", new { id = @Model.AnimalId }))
    {
      <input type="Submit" value="Delete this item">
    }
    <hr>
    @Html.ActionLink("Edit","Edit","Animals",new {id = @Model.AnimalId})
  }
  else if(values.Item1 == true && values.Item2 == false)
  {
    <div>
      <p>Your login token has expired. @Html.ActionLink("login","Login","Security") again to add new animals</p>
    </div>
  }
  else
  {
    <div>
      <p>You must @Html.ActionLink("login","Login","Security") in order to post animals</p>
    </div>
  }
<hr>
}

AnimalShelterClient.Solution/AnimalShelterClient/Views/Animals/Edit.cshtml
@using AnimalShelterClient.Models
@model AnimalShelterClient.Models.Animal

@{
  (bool,bool) values = Payload.GetValues(Context);
  @if(values.Item1 == true && values.Item2 == true)
  {
    @using(@Html.BeginForm())
    {
      @Html.HiddenFor(x => x.AnimalId)
      @Html.LabelFor(x => x.Name)
      @Html.EditorFor(x => x.Name)
      @Html.LabelFor(x => x.AnimalType)
      @Html.EditorFor(x => x.AnimalType)
      <input type="submit" value="Edit this animal profile">
    }
  }
  else if(values.Item1 == true && values.Item2 == false)
  {
    <div>
      <p>Your login token has expired. @Html.ActionLink("login","Login","Security") again to add new animals</p>
    </div>
  }
  else
  {
    <div>
      <p>You must @Html.ActionLink("login","Login","Security") in order to post animals</p>
    </div>
  }
  <hr>
}

AnimalShelterClient.Solution/AnimalShelterClient/Views/Animals/Index.cshtml
@using AnimalShelterClient.Models

@{
  (bool,bool) values = Payload.GetValues(Context);

  @if(values.Item1 == true && values.Item2 == true)
  {
    <div>
      <p>@Html.ActionLink("Enter a new animal","Create")</p>
    </div>
  }
  else if(values.Item1 == true && values.Item2 == false)
  {
    <div>
      <p>Your login token has expired. @Html.ActionLink("login","Login","Security") again to add new animals</p>
    </div>
  }
  else
  {
    <div>
      <p>You must @Html.ActionLink("login","Login","Security") in order to post animals</p>
    </div>
  }
<hr>
}

@foreach(Animal a in @Model)
{
  <p>@Html.ActionLink(a.Name,"Details",new {id = a.AnimalId})</p>
}